kind: ConfigMap
apiVersion: v1
metadata:
  name: chat-doc-configmap
  namespace: llm-rag
data:
  INFERENCE_SERVER_URL: 'https://llm-modelserver-llm.apps.rosa-ltrwt.2rfo.p1.openshiftapps.com/api/v1/task/text-generation:443'
  REDIS_HOST: redis-stack-server.redis.svc.cluster.local
